settings:
    afksystem:
        enable: true
    chatping:
        enable: true
    smeltingpatch:
        enable: true

database:
    MySQL:
        host:
        port:
        database:
        user:
        password: