name: Nebula
version: '${project.version}'
main: org.nebulamc.plugin.Nebula
api-version: 1.19
description: The main plugin for NebulaMC.
authors: [ Spectrobyte, smartfrigde, abbysrc ]
commands:
  spawnchest:
    description: Spawns a chest in the world randomly.
    usage: /<command>
    permission: nebula.spawnchest
  spawnmineshafts:
    description: Spawns mineshafts in the world.
    usage: /<command>
    permission: nebula.spawnmineshafts
  setpronouns:
    description: Coming soon!
    usage: /<command>
    permission: nebula.setpronouns
  wager:
    aliases: [ homosex, getbitches ]
    description: Wagers an item with a player.
    usage: /<command> [<player>]
  giveitem:
    description: Gives a custom item to the player.
    usage: /<command> [<player>] [<item>]
    permission: nebula.giveitem
  arename:
    aliases: [ adminrename ]
    description: Renames the held item. For admin use only.
    usage: /<command> [<string>]
    permission: nebula.arename